### ISSUE TITLE
os.path.relpath ValueError

### ISSUE THREAD

**Issue by SamWindell** [jimporter/bfg9000#117]
Hi, seems to be an error with displaying error messages. I have a bfg script which has a syntax error in it. But it seems it can't show me this error because my code directory is on my G drive and the BFG source is on my C drive, so os.path.relpath is producing an error.

https://github.com/jimporter/bfg9000/blob/aaa3592ccb9fb179d52675f380f707b4634e0686/bfg9000/log.py#L15

```Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\Scripts\9k.exe\__main__.py", line 9, in <module>
  File "c:\python27\lib\site-packages\bfg9000\driver.py", line 320, in simple_main
    return configure(parser, parser, args, extra)
  File "c:\python27\lib\site-packages\bfg9000\driver.py", line 204, in configure
    logger.exception(e)
  File "c:\python27\lib\logging\__init__.py", line 1200, in exception
    self.error(msg, *args, **kwargs)
  File "c:\python27\lib\logging\__init__.py", line 1193, in error
    self._log(ERROR, msg, args, **kwargs)
  File "c:\python27\lib\logging\__init__.py", line 1286, in _log
    self.handle(record)
  File "c:\python27\lib\logging\__init__.py", line 1296, in handle
    self.callHandlers(record)
  File "c:\python27\lib\logging\__init__.py", line 1336, in callHandlers
    hdlr.handle(record)
  File "c:\python27\lib\logging\__init__.py", line 759, in handle
    self.emit(record)
  File "c:\python27\lib\site-packages\bfg9000\log.py", line 67, in emit
    pre, stack, post = _filter_stack(record.full_stack)
  File "c:\python27\lib\site-packages\bfg9000\log.py", line 20, in _filter_stack
    if not _is_bfg_src(line[0]):
  File "c:\python27\lib\site-packages\bfg9000\log.py", line 12, in _is_bfg_src
    rel = os.path.relpath(filename, os.path.dirname(__file__))
  File "c:\python27\lib\ntpath.py", line 529, in relpath
    % (path_prefix, start_prefix))
ValueError: path is on drive G:, start on drive c:```

**Comment by jimporter** [comment]
Thanks for the catch! I'll push a patch shortly. Just want to make sure the other uses of `relpath` are safe...
