### ISSUE TITLE
Crash when using Ninja from Git

### ISSUE THREAD

**Issue by kirbyfan64** [jimporter/bfg9000#68]
My Ninja version looks like this:

```
ryan@DevPC-LX:~/plax2$ ninja --version
1.5.3.git
ryan@DevPC-LX:~/plax2$ 
```

bfg9000 apparently doesn't like that too much:

```
ryan@DevPC-LX:~/plax2$ bfg9000 --help
Traceback (most recent call last):
  File "/media/ryan/stuff/anaconda/bin/bfg9000", line 9, in <module>
    load_entry_point('bfg9000==0.2.0.dev0', 'console_scripts', 'bfg9000')()
  File "/media/ryan/stuff/anaconda/lib/python3.4/site-packages/bfg9000-0.2.0.dev0-py3.4.egg/bfg9000/driver.py", line 90, in main
    backends = get_backends()
  File "/media/ryan/stuff/anaconda/lib/python3.4/site-packages/bfg9000-0.2.0.dev0-py3.4.egg/bfg9000/backends/__init__.py", line 16, in get_backends
    backends.sort(key=sort_key, reverse=True)
  File "/media/ryan/stuff/anaconda/lib/python3.4/site-packages/bfg9000-0.2.0.dev0-py3.4.egg/bfg9000/backends/__init__.py", line 15, in sort_key
    return x[1].priority if x[1].version() else 0
  File "/media/ryan/stuff/anaconda/lib/python3.4/site-packages/bfg9000-0.2.0.dev0-py3.4.egg/bfg9000/backends/ninja/writer.py", line 23, in version
    return Version(output.strip())
  File "/media/ryan/stuff/anaconda/lib/python3.4/site-packages/packaging-16.5-py3.4.egg/packaging/version.py", line 202, in __init__
packaging.version.InvalidVersion: Invalid version: '1.5.3.git'
ryan@DevPC-LX:~/plax2$ 
```

**Comment by jimporter** [comment]
Yeah, all the versions are assumed to be valid according to Python's rules for versioning, and that's not valid. I'll have to write my own version parser I guess.
