### ISSUE TITLE
lxml dependency shouldn't be extra

### ISSUE THREAD

**Issue by jmgao** [jimporter/bfg9000#92]
Running `bfg9000` on linux after `pip install bfg9000`:
```
Traceback (most recent call last):
  File "/home/jmgao/.local/bin/bfg9000", line 11, in <module>
    sys.exit(main())
  File "/home/jmgao/.local/lib/python2.7/site-packages/bfg9000/driver.py", line 209, in main
    add_configure_args(conf_p)
  File "/home/jmgao/.local/lib/python2.7/site-packages/bfg9000/driver.py", line 113, in add_configure_args
    backends = list_backends()
  File "/home/jmgao/.local/lib/python2.7/site-packages/bfg9000/backends/__init__.py", line 14, in list_backends
    backend = i.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/jmgao/.local/lib/python2.7/site-packages/bfg9000/backends/msbuild/writer.py", line 7, in <module>
    from .syntax import *
  File "/home/jmgao/.local/lib/python2.7/site-packages/bfg9000/backends/msbuild/syntax.py", line 7, in <module>
    from lxml import etree
ImportError: No module named lxml
```

**Comment by jimporter** [comment]
What version of bfg are you on? This should be fixed on master (it's technically a bug in setuptools, but I worked around it).

**Comment by jmgao** [comment]
The one that installed via pip, which is presumably 0.2.0
